<?php
/**
 * CakePHP Plugin : CakePHP Subdomain Routing
 * Copyright (c) Multidimension.al (http://multidimension.al)
 * Github : https://github.com/multidimension-al/cakephp-subdomains
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE file
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     (c) Multidimension.al (http://multidimension.al)
 * @link          https://github.com/multidimension-al/cakephp-subdomains Github
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

/*/
 *  DEFAULT 'subdomains.php' config file.
 *
 *  This file is normally generated by running the following command in shell:
 *  bin/cake SubdomainsInstall
 *
 *  If you don't have this file, copy it to your main CakePHP config folder.
/*/

return array(
    'Multidimensional/Subdomains' => 
        array('subdomains' =>
            array('{SUBDOMAIN_1}', '{SUBDOMAIN_2}', /*...*/ '{SUBDOMAIN_N}')
        )
    );